name: gsd-yesod
version: "0.0.1"

dependencies:
- base
- aeson
- bytestring
- configurator
- yesod-core
- yesod-persistent
- esqueleto
- monad-logger
- persistent
- persistent-postgresql
- text
- time
- fast-logger
- warp
- wai
- wai-extra
- wai-logger

# The library contains all of our application code.
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -ddump-splices
  - -ddump-to-file
  - -fwarn-tabs
  - -O2

# Runnable executable for our application
# This is just a thin wrapper over the library.
executables:
  gsd-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gsd-yesod

# Test suite
tests:
  gsd-yesod-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - gsd-yesod
    - hspec >= 2.0.0
    - mtl
    - shakespeare
    - yesod-test
